### ISSUE TITLE
feat: Tag, Calendar 관련 Input 기능 추가

### ISSUE THREAD

**Issue by Sfer7** [sprint-part3-team1/Planyang#28]
## 📝 이슈 요약

- 기존 Input 태그에 추가 기능 구현

## ✅ 체크 리스트

- [x] Tag 관련 Input 기능 구현
- [x] Calendar 관련 Input 기능 구현

**Comment by minjeong9919** [comment]
엇 준영님 이거 혹시 하고 계신가요??
제가 이거 구현중이라서!! 

![image](https://github.com/sprint-part3-team1/Planyang/assets/110798291/75aba7ea-990f-4d0f-b8a4-91e4f3a297cd)

이 부분 하고 계시는거 맞나용?

**Comment by minjeong9919** [comment]
준영님 하고 계시다면 제가 저 부분만 빼고 다른 거 할게요!
